esphome:
  name: volume1

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Volume1 Fallback Hotspot"
    password: !secret ap_password

binary_sensor:
  - platform: gpio
    id: button_kitchen
    pin:
      number: GPIO37
      mode: INPUT_PULLUP
      inverted: True
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - homeassistant.service:
            service: media_player.media_next_track
            data:
              entity_id: media_player.upstairs_stereo_roon
        - logger.log: "double click - next track"
    - timing:
      - ON for at most .49s
      - OFF for at least 0.25s
      then:
        - homeassistant.service:
            service: media_player.media_play_pause
            data:
              entity_id: media_player.upstairs_stereo_roon
        - logger.log: "single click - play/pause"

sensor:
  - platform: rotary_encoder
    id: knob_kitchen
    pin_a:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: false
    pin_b:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: false
    resolution: 1
    min_value: -3
    max_value: 3
    on_value_range:
      - above: 2
        then:
          - script.execute: volume_up
      - below: -2
        then:
          - script.execute: volume_down
              
script:
  - id: volume_up
    then:
      - homeassistant.service:
          service: media_player.volume_up
          data:
            entity_id: media_player.living_room
      - logger.log: "vol up trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_kitchen
          value: 0
  - id: volume_down
    then:
      - homeassistant.service:
          service: media_player.volume_down
          data:
            entity_id: media_player.living_room
      - logger.log: "vol down trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_kitchen
          value: 0
